In [9]:
import numpy as np

作業目標<br>
讀取存取陣列資料<br>
作業重點<br>
多陣列存一起需要存成npz，讀取須注意npz中有多個陣列

題目:<br>
1. 將下兩列array存成npz檔<br>
array1 = np.array(range(30))<br>
array2 = np.array([2,3,5])<br>
2. 讀取剛剛的npz檔，加入下列array一起存成新的npz檔


In [10]:
#. 將下兩列array存成npz檔
array1 = np.array(range(30))
array2 = np.array([2,3,5])
np.savez("array_save.npz", array1, array2)

In [11]:
#2. 讀取剛剛的npz檔，加入下列array一起存成新的npz檔
array=np.load("array_save.npz")
array3 = np.array([[4,5,6],[1,2,3]])
np.savez("new_array_save.npz", array['arr_0'], array['arr_1'], array3)

In [12]:
array4= np.load("new_array_save.npz")
array4.files
print(array4['arr_0'])
print(array4['arr_1'])
print(array4['arr_2'])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[2 3 5]
[[4 5 6]
 [1 2 3]]
